services:
  build-ran-base:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.base.ubuntu22
      tags:
        - ran-base:latest
  build-softmodems:
    image: ran-base:latest
    volumes:
      - ../../:/oai-ran/
      - ~/.cache/:/root/.cache/
    command: bash -c "git config --global --add safe.directory /oai-ran &&
      source oaienv && \
      cd cmake_targets && \
      mkdir -p log && \
      ./build_oai -c --ninja \
        --eNB --gNB --RU --UE --nrUE \
        --build-lib "telnetsrv enbscope uescope nrscope" \
        -w USRP -t Ethernet \
        --build-e2 --cmake-opt -DXAPP_MULTILANGUAGE=OFF \
        --noavx512 \
        --cmake-opt -DCMAKE_C_FLAGS="-Werror" --cmake-opt -DCMAKE_CXX_FLAGS="-Werror" $BUILD_OPTION"
  build-nr-ue-image:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.nrUE.ubuntu22
      tags:
        - oai-nr-ue:latest
    entrypoint: ""
    command: echo "build successful"
  build-gnb-image:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.gNB.ubuntu22
      tags:
        - oai-gnb:latest
    entrypoint: ""
    command: echo "build successful"
  build-lte-ru-image:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.lteRU.ubuntu22
      tags:
        - oai-lte-ru:latest
    entrypoint: ""
    command: echo "build successful"
  build-lte-ue-image:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.lteUE.ubuntu22
      tags:
        - oai-lte-ue:latest
    entrypoint: ""
    command: echo "build successful"
  build-enb-image:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.eNB.ubuntu22
      tags:
        - oai-enb:latest
    entrypoint: ""
    command: echo "build successful"
  build-cuup-image:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.nr-cuup.ubuntu22
      tags:
        - oai-cuup-ru:latest
    entrypoint: ""
    command: echo "build successful"
